# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.BooleanField()),
                ('birth', models.DateField()),
                ('location', models.CharField(max_length=50, null=True)),
                ('institution', models.CharField(max_length=150, null=True)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('maxsize', models.IntegerField()),
                ('identifier', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('deprecated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('is_creator', models.BooleanField()),
                ('is_joined', models.BooleanField()),
                ('created_time', models.DateTimeField()),
                ('joined_time', models.DateTimeField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('confirmed_time', models.DateTimeField(null=True)),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField()),
                ('is_valid', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('link_me', models.BooleanField()),
                ('see_my_global', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='memberrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human.Group'),
        ),
        migrations.AddField(
            model_name='link',
            name='source_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_member', to='Human.GroupMember'),
        ),
        migrations.AddField(
            model_name='link',
            name='target_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_member', to='Human.GroupMember'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extra',
            name='privacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human.Privacy'),
        ),
        migrations.AddField(
            model_name='credits',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Human.Link'),
        ),
        migrations.AddField(
            model_name='credits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
