# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacy',
            name='link_me',
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='see_my_global',
        ),
        migrations.AddField(
            model_name='privacy',
            name='allow_group_recommendation',
            field=models.BooleanField(default=True, verbose_name=b'Group Recommendation'),
        ),
    ]
