# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 20:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friendnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('group_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='friendnet.GroupMember')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='friendnet.Group')),
                ('authenticated', models.BooleanField()),
                ('template', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
