USE lineme;

ALTER TABLE auth_user AUTO_INCREMENT = 10000;
ALTER TABLE human_extra AUTO_INCREMENT = 10000;
ALTER TABLE human_privacy AUTO_INCREMENT = 10000;
ALTER TABLE human_group AUTO_INCREMENT = 10000;
ALTER TABLE human_groupmember AUTO_INCREMENT = 10000;
ALTER TABLE human_link AUTO_INCREMENT = 10000;
